```{r set}
#| include: false 
library(tidyverse) 
library(sf)
```

# Data

## Plots

```{r plots}
#| message: false
#| warning: false
#| fig-cap: "Caption."
ci <- read_sf("data/ci/COTE D'IVE.shp")
plots <- read_csv2("data/all_plot_corr.csv") %>% 
  select(-1) %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>% 
  mutate(system = gsub("_", " ", system))
ggplot(plots) +
  geom_sf(data = ci) +
  geom_sf(aes(col = system)) +
  theme_bw() +
  scale_color_discrete("")
```

## Trees

> Questions:
>
> - What to do with NA origins (338 trees, 90 plots from AimeK database)
> - What to do with NA dbh (239 trees, 27 plots from AimeK database)
> - What to do with NA h (178 trees, 61 plots from AimeK database)
> - What to do with NA dbh & h (55 trees, 18 plots from AimeK database)

```{r trees}
#| message: false
#| warning: false
#| fig-cap: "Caption."
trees <- read_csv2("data/all_tree_corr.csv") %>% 
  select(-1) %>% 
  mutate(system = gsub("_", " ", system)) %>% 
  select(database, id_plot, id_tree, system, origin, dbh, H, genusCorr, speciesCorr) %>% 
  rename(h = H, genus = genusCorr, species = speciesCorr)
trees$wd <- BIOMASS::getWoodDensity(genus = trees$genus,
                                    species = trees$species,
                                    stand = trees$id_plot)$meanWD
trees %>% 
  ggplot(aes(dbh, h, col = origin)) +
  geom_point(alpha = .1) +
  facet_wrap(~ system) +
  theme_bw() +
  geom_smooth(method = "lm", formula = y ~ log(x)) +
  xlab("dbh [ cm ]") + ylab("h [ m ]") +
  theme(legend.position = c(0.8, 0.2))
```

## Biomass

$$AGB = 0.0673 \times (wd \times dbh^2 \times h)^{0.976}$$

Following @chave2014

```{r biomass}
#| message: false
#| warning: false
#| fig-cap: "Caption."
biomass <- trees %>% 
  mutate(agb = 0.0673*(wd*dbh^2*h)^0.976) %>% 
  group_by(database, system, id_plot) %>% 
  summarise(agb = sum(agb, na.rm = TRUE)/10^3) %>% 
  left_join(select(read_csv2("data/all_plot_corr.csv"), id_plot, area_plot.ha, long, lat)) %>% 
  mutate(agb = agb/area_plot.ha)
biomass %>% 
  filter(agb < 1000, agb > 10) %>% 
  na.omit() %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>% 
  ggplot() +
  geom_sf(data = ci) +
  geom_sf(aes(col = agb)) +
  theme_bw() +
  scale_color_viridis_c("AGB [ t / ha ]", trans = "log")
```

```{r biomass_hist}
#| message: false
#| warning: false
#| fig-cap: "Caption."
biomass %>% 
  ggplot(aes(agb, fill = system)) +
  geom_histogram() +
  scale_x_log10() +
  theme_bw() +
  geom_vline(xintercept = c(10, 1000)) +
  xlab("AGB [ t / ha ]")
```

> Questions
>
> - What to do with 160 plots with AGB\<10t/ha: 28 agroforestry from AimeK, 13 young sf from Amani, 5 plantation from ForestInnov_Lataha, 5 young sf from Nguessan and 96 agroforestry from Sanial
> - What to do with 160 plots with AGB\>1000t/ha: 1 forest from Amani

```{r biomass_hist_sel}
#| message: false
#| warning: false
#| fig-cap: "Caption."
biomass %>%
  filter(agb < 1000, agb > 10) %>% 
  ggplot(aes(agb, fill = system)) +
  geom_histogram() +
  scale_x_log10() +
  theme_bw() +
  xlab("AGB [ t / ha ]")
```
