```{r set}
#| include: false 
library(tidyverse) 
library(cmdstanr)
```

# System-Origin model

$$
h = \gamma_s \times \gamma_p \times \frac{\alpha_f \times dbh}{\beta_f+dbh} \\
\alpha_f \sim \mathcal N (\alpha_0,\sigma_f) \\
\beta_f \sim \mathcal N (\beta_0,\sigma_f)
$$

```{r sample}
#| eval: false
data <- readRDS("data/sub.mod.data.1")
model <- cmdstan_model("models/factor.stan")
path <- "chains/systemorigin"
if(file.exists(path))
  unlink(path, recursive = TRUE)
dir.create(path)
fit <- model$sample(
    data = list(
      N = nrow(data),
      P = max(data$num_plot),
      S = max(data$num_species),
      "F" = max(data$systori),
      plot = data$num_plot,
      species = data$num_species,
      factor = data$systori,
      h = data$H,
      dbh = data$dbh
    ),
    chains = 4,
    parallel_chains = 4,
    save_warmup = FALSE,
    output_dir = path,
    refresh = 100
  )
```

```{r fit}
data <- readRDS("data/sub.mod.data.1")
fit <- as_cmdstan_fit(list.files("chains/systemorigin", full.names = TRUE))
fit
```

```{r pvo}
#| fig-cap: "Predicted vs. observed."
fit$summary("y_p", "median") %>% 
  mutate(obs = data$H) %>% 
  ggplot(aes(median, obs)) +
  geom_abline() +
  geom_point() +
  theme_bw() +
  scale_x_log10() +
  scale_y_log10() +
  xlab("Predicted") + ylab("Observed")
```
