```{r set}
#| include: false 
library(tidyverse) 
library(cmdstanr)
```

# Exploration

Full model system-origin:

$$
h = \gamma_s \times \gamma_p \times \frac{\alpha_f \times dbh}{\beta_f+dbh} \\
\alpha_f \sim \mathcal N (\alpha_0,\sigma_f) \\
\beta_f \sim \mathcal N (\beta_0,\sigma_f)
$$

```{r alpha_beta}
#| message: false
#| warning: false
data <- readRDS("data/sub.mod.data.1")
fit <-  as_cmdstan_fit(list.files("chains/systemorigin_reduced", full.names = TRUE))
fit$summary(c("alpha_f", "beta_f"), 
            quantiles = ~ posterior::quantile2(., probs = c(0.05, 0.25, 
                                                            0.5, 0.75, 0.95))) %>% 
  separate(variable, c("parameter", "f", "systori"), convert = TRUE) %>% 
  select(-f) %>% 
  left_join(select(data, system, origin, systori) %>% unique()) %>% 
  select(-systori) %>% 
  gather(quantile, value, -parameter, -system, -origin) %>% 
  mutate(system = gsub("_", " ", system)) %>% 
  mutate(metric = paste0(parameter, "_", quantile)) %>% 
  select(-parameter, -quantile) %>% 
  pivot_wider(names_from = metric, values_from = value) %>% 
  ggplot(aes(beta_q50, alpha_q50,
             col = paste0(system, "\n", origin),
             label = paste0(system, "\n", origin))) +
  geom_segment(aes(x = beta_q25, xend = beta_q75)) +
  geom_segment(aes(x = beta_q5, xend = beta_q95), size = .2) +
  geom_segment(aes(y = alpha_q25, yend = alpha_q75)) +
  geom_segment(aes(y = alpha_q5, yend = alpha_q95), size = .2) +
  geom_point() +
  ggrepel::geom_text_repel(box.padding = 0.4, ) +
  theme_bw() +
  scale_color_discrete(guide = "none") +
  ylab("Asymptotic height [ m ]") +
  xlab("Diameter at 50% height [ cm ]")
```
