project:
  type: book
  output-dir: docs

book:
  title: "C4F - Tree Allometry"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - 01_data.qmd
    - 02_model.qmd
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1
    number-sections: false

editor: visual
